### PR TITLE
#18: Convert names to upper case

### LINKED ISSUE #18: Improve mapping of table and column names: map all names to upper case
Table names in Databricks are always `lower_case` while column names can be `MIXED_case`. The adapter reports these names 1:1 to Exasol. When querying a virtual table, e.g. using `select * from vs.table` it will fail, because Exasol automatically converts unquoted names to upper case `TABLE` and the query fails with error `object VS.TABLE not found`.

To simplify using the VS we should automatically convert table and column names to upper case.

### PR DESCRIPTION
**Pull request by kaklakariada**
Closes #18

### CODE REVIEW

File: src/test/java/com/exasol/adapter/databricks/PushdownQueryIT.java [hunk 1]
```diff
@@ -17,9 +17,9 @@
 class PushdownQueryIT extends AbstractIntegrationTestBase {
 
     @TestFactory
-    Stream<DynamicNode> selectlistFilterOrderLimit() {
+    Stream<DynamicNode> selectListFilterOrderLimit() {
         return testSetup
-                .pushdownTest(databricksSchema -> databricksSchema.createTable("tab", "ID", "INT", "NAME", "STRING")
+                .pushdownTest(databricksSchema -> databricksSchema.createTable("tab", "id", "INT", "name", "STRING")
```
Comment (kaklakariada) [inline src/test/java/com/exasol/adapter/databricks/PushdownQueryIT.java:22]: Intentionally use lower case table & column in databricks to verify, that pushdown query contains lowercase names.

File: src/test/java/com/exasol/adapter/databricks/PushdownQueryIT.java [hunk 2]
```diff
@@ -32,15 +32,15 @@ Stream<DynamicNode> selectlistFilterOrderLimit() {
 
                 .capability("SELECTLIST_PROJECTION").info("single column").query("SELECT id FROM $tab")
                 .expect(table("BIGINT").row(1L).row(2L).row(3L).matchesInAnyOrder())
-                .expectPushdown(startsWith("SELECT `tab`.`ID` FROM"))
+                .expectPushdown(startsWith("SELECT `tab`.`id` FROM"))
```
Comment (kaklakariada) [inline src/test/java/com/exasol/adapter/databricks/PushdownQueryIT.java:35]: Verify that pushdown query uses the same lowercase as databricks

**Review by pj-spoelders — APPROVED** [review]
Looks good!
